### PR TITLE
Keep working on Scheduler

### PR DESCRIPTION
**Pull request by ichayer**
I open this PR so that we can communicate and beautify this branch before making a merge because it is quite messy

### CODE REVIEW

**Comment by ichayer** [comment]
Hey @camilaDiToro exceptions are now working again :)

I dont understand why in _kernel.c_, line 99, process is not being killed:

The printA process now prints an A every second and at a certain point is being killed. Then, I call the scheduler to choose the shell again but printA process is still alive.

**Comment by ichayer** [comment]
**Update:** 

Everything that is after the `_sti()` **never** runs again. Apparently kernel's main is never choosen again by the scheduler. 

This can be reproduced by doing a long for with a `scr_clear()` in the for's body before and after `sti()`.

**Comment by camilaDiToro** [comment]
> **Update:**
> 
> Everything that is after the `_sti()` **never** runs again. Apparently kernel's main is never choosen again by the scheduler.
> 
> This can be reproduced by doing a long for with a `scr_clear()` in the for's body before and after `sti()`.

You said in whats app: "El Kernel no deberia ser considerado un proceso" 

Now its not being considered as a process. And thats why, once its interrupted by the timer tick, its never choosen again.

This causes that the rip never points again to the point where the process was interrupted, and this happens because the scheduler pops a new set of registers that make the so execute the other processes (shell and printA). After that, the sch chooses between its ready processes and the kernel is not there. 

Note that a proces CAN be killed from the shell if a proper syscall is setted. Ive just tested that. I made the time syscall to call the function that kills a process just to test. It worked.

**Comment by ichayer** [comment]
> > ```
> > void sch_yieldProcess(){
> >     currentRunningProcessPID = -1;
> > 
> >     // TO DO: try to avoid ticking.
> >     _int20();
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > By the way the scheduling is working now, i think that this funciton should set the quantums to 0. If you make currentRunningProcessPid=-1, the rsp wont be actualizer. Chech the first two lines of `sch_switchProcess`
> > Forcing the timer tick just makes the yield inmediate. You could just wait for the next tick if you want to "avoid ticking"
> 
> If you think this is ok i can make a push with this change and the alignment of the naming convention

Yep. Actually setting `currentRunningProcessPID` to -1 will not update the quantums variable. I mean, each time the process gets rid of the CPU, it will keep the remaining amount of quantums.

**Comment by ichayer** [comment]
> You didnt mention anything about pushing the commits.

Yes I did, check my reaction in the comment i ping:

> If you think this is ok i can make a push with this change and the alignment of the naming convention

**Pull request merged**
